<template>
  <v-content>
    <v-container 
      fluid 
      fill-height>
      <v-layout
        justify-center
        align-center
      >
        <v-flex 
          text-xs-center 
          sm5
          pa-5>
          <v-card>
            <h1>Welcome to NEAT Builder!</h1>
          </v-card>
        </v-flex>
      </v-layout>
    </v-container>
  </v-content>
</template>
